import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

const routeRoot = "app/api/admin/materials/[id]/upload";
const preparePath = `${routeRoot}/prepare/route.ts`;
const finalizePath = `${routeRoot}/finalize/route.ts`;
const cancelPath = `${routeRoot}/cancel/route.ts`;
const clientPath = "app/quan-tri/catalog/material-upload-form.tsx";
const storagePath = "lib/storage/material-storage.ts";
const repositoryPath = "lib/repositories/material-asset-repository.ts";
const typesPath = "lib/supabase/database.types.ts";
const migrationPath = "supabase/migrations/0033_material_direct_upload_sessions.sql";

async function source(file: string): Promise<string> { return readFile(file, "utf8"); }
function order(code: string, needles: string[]): void {
  let previous = -1;
  for (const needle of needles) {
    const next = code.indexOf(needle);
    assert.ok(next > previous, `${needle} must follow the previous upload step`);
    previous = next;
  }
}

test("approved admin can prepare an upload through JSON-only server metadata", async () => {
  const code = await source(preparePath);
  assert.match(code, /getAccountAccess/);
  assert.match(code, /access\.profile\?\.role !== "admin"/);
  order(code, ["const input = await readPrepareBody", "await isMaterialProduct", "await reserveMaterialAssetUpload", "await createMaterialUploadCapability", "return Response.json({ reservationId"]);
  assert.doesNotMatch(code, /formData|arrayBuffer|new File|Blob/);
});

test("unauthorized users cannot prepare or finalize", async () => {
  const [prepare, finalize, cancel] = await Promise.all([source(preparePath), source(finalizePath), source(cancelPath)]);
  for (const code of [prepare, finalize, cancel]) {
    assert.match(code, /access\.status === "unauthenticated"/);
    assert.match(code, /access\.profile\?\.role !== "admin"/);
  }
});

test("nonexistent and foreign materials are rejected by trusted material and session binding", async () => {
  const [prepare, finalize] = await Promise.all([source(preparePath), source(finalizePath)]);
  assert.match(prepare, /isMaterialProduct\(productId\)/);
  assert.match(finalize, /reservation\.productId !== productId/);
  assert.match(finalize, /existing\?\.product_id === productId/);
});

test("invalid MIME and both business size ceilings remain enforced", async () => {
  const [prepare, repository, storage] = await Promise.all([source(preparePath), source(repositoryPath), source("lib/storage/material-upload-constants.ts")]);
  assert.match(prepare, /isSupportedMaterialMimeType\(input\.mimeType\)/);
  assert.match(prepare, /input\.byteSize > materialSizeLimit\(input\.mimeType\)/);
  assert.match(repository, /materialSizeLimit\(input\.mimeType\)/);
  assert.match(storage, /MAX_PDF_BYTES = 20 \* 1024 \* 1024/);
  assert.match(storage, /MAX_VIDEO_BYTES = 500 \* 1024 \* 1024/);
});

test("arbitrary client storage paths are not accepted and paths are generated by reservation", async () => {
  const code = await source(preparePath);
  assert.match(code, /Object\.keys\(body\)\.length !== 3/);
  assert.doesNotMatch(code, /body\.storagePath|body\.path/);
  assert.match(code, /reservation\.storagePath/);
});

test("prepare returns bounded JSON metadata and a signed capability only", async () => {
  const code = await source(preparePath);
  assert.match(code, /upload: \{ bucket: MATERIALS_BUCKET, path: capability\.storagePath, token: capability\.token \}/);
  assert.match(code, /expiresIn: MATERIAL_UPLOAD_EXPIRES_IN_SECONDS/);
  assert.doesNotMatch(code, /SUPABASE_SERVICE_ROLE_KEY/);
});

test("finalize resolves the session server-side, verifies object metadata, then commits", async () => {
  const code = await source(finalizePath);
  order(code, ["reservation = await getMaterialAssetUploadReservation", "const object = await getMaterialObjectInfo", "const asset = await finalizeMaterialAssetUpload"]);
  assert.match(code, /object\.storagePath !== reservation\.storagePath/);
  assert.match(code, /object\.mimeType !== reservation\.mimeType/);
  assert.match(code, /object\.byteSize !== reservation\.byteSize/);
});

test("missing, wrong, expired, cancelled, and foreign sessions fail without provider leakage", async () => {
  const [finalize, cancel] = await Promise.all([source(finalizePath), source(cancelPath)]);
  assert.match(finalize, /if \(!reservation\)/);
  assert.match(finalize, /Date\.parse\(reservation\.expiresAt\) <= Date\.now\(\)/);
  assert.match(finalize, /removeNewMaterialObject/);
  assert.match(finalize, /releaseMaterialAssetUpload/);
  assert.match(cancel, /releaseMaterialAssetUpload/);
  assert.match(finalize, /Unable to finalize material upload/);
});

test("duplicate finalize is idempotent and cannot create a duplicate version", async () => {
  const [finalize, repository, migration] = await Promise.all([source(finalizePath), source(repositoryPath), source(migrationPath)]);
  assert.match(finalize, /getMaterialAssetByUploadReservation/);
  assert.match(repository, /eq\("upload_reservation_id", reservationId\.toLowerCase\(\)\)/);
  assert.match(migration, /CREATE UNIQUE INDEX material_assets_upload_reservation_id_unique/);
  assert.match(migration, /IF FOUND THEN RETURN v_row/);
});

test("the direct storage capability is server-only and the bucket remains private", async () => {
  const [storage, client, migration] = await Promise.all([source(storagePath), source(clientPath), source("supabase/migrations/0012_private_material_storage.sql")]);
  assert.match(storage, /createServerAdminClient\(\)/);
  assert.doesNotMatch(client, /SUPABASE_SERVICE_ROLE_KEY|server-admin|material-storage/);
  assert.match(client, /uploadToSignedUrl/);
  assert.match(migration, /public = false/);
});

test("the API routes never receive the complete binary file", async () => {
  const codes = await Promise.all([source(`${routeRoot}/route.ts`), source(preparePath), source(finalizePath), source(cancelPath)]);
  for (const code of codes) assert.doesNotMatch(code, /request\.formData|request\.arrayBuffer|\.arrayBuffer\(\)|instanceof File|instanceof Blob|multipart\/form-data/);
  assert.match(await source(clientPath), /JSON\.stringify\(\{ originalName: file\.name, mimeType: file\.type, byteSize: file\.size \}\)/);
});

test("direct upload failure does not commit metadata and retry can prepare a new session", async () => {
  const [client, finalize] = await Promise.all([source(clientPath), source(finalizePath)]);
  assert.match(client, /if \(error\)/);
  assert.match(client, /cancel\(reservationId\)/);
  assert.match(finalize, /getMaterialObjectInfo/);
  assert.match(finalize, /finalizeMaterialAssetUpload/);
});

test("the client performs prepare, direct upload, then finalize in order", async () => {
  const code = await source(clientPath);
  order(code, ["/upload/prepare", "uploadToSignedUrl", "/upload/finalize"]);
  assert.match(code, /disabled=\{active\}/);
  assert.match(code, /setState\("uploading"\)/);
  assert.match(code, /setState\("success"\)/);
  assert.match(code, /setState\("error"\)/);
});

test("the client never sends a File object to a Vercel API route", async () => {
  const code = await source(clientPath);
  assert.doesNotMatch(code, /body:\s*file/);
  assert.doesNotMatch(code, /FormData/);
  assert.match(code, /byteSize: file\.size/);
  assert.match(code, /uploadToSignedUrl\(upload\.path, upload\.token, file/);
});

test("product/material/path binding and version idempotency remain in repository and SQL contracts", async () => {
  const [repository, migration, types] = await Promise.all([source(repositoryPath), source(migrationPath), source(typesPath)]);
  assert.match(repository, /isValidMaterialStoragePathForProductAndVersion/);
  assert.match(migration, /v_reservation\.product_id/);
  assert.match(migration, /v_reservation\.storage_path/);
  assert.match(migration, /v_reservation\.version/);
  assert.match(types, /upload_reservation_id: string \| null/);
  assert.match(types, /expires_at: string/);
});

test("concurrent version reservation remains delegated to the existing advisory-lock RPC", async () => {
  const [repository, migration] = await Promise.all([source(repositoryPath), source("supabase/migrations/0029_material_storage_integrity_boundary.sql")]);
  assert.match(repository, /reserve_material_asset_upload/);
  assert.match(migration, /pg_advisory_xact_lock/);
  assert.match(migration, /UNIQUE \(product_id, version\)/);
});

test("failed upload cleanup safely removes the exact object and releases the reservation", async () => {
  const [finalize, cancel, storage] = await Promise.all([source(finalizePath), source(cancelPath), source(storagePath)]);
  assert.match(finalize, /removeNewMaterialObject\(reservation\.storagePath\)/);
  assert.match(finalize, /releaseMaterialAssetUpload\(reservation\.reservationId\)/);
  assert.match(cancel, /removeNewMaterialObject\(reservation\.storagePath\)/);
  assert.match(storage, /remove\(\[storagePath\]\)/);
});

test("existing signed read URL and entitlement route remain unchanged in scope", async () => {
  const code = await source("app/api/materials/[id]/signed-url/route.ts");
  assert.match(code, /getActiveProductEntitlement/);
  assert.match(code, /createMaterialSignedUrl/);
});

test("finalize checks the authenticated material session before touching storage", async () => {
  const code = await source(finalizePath);
  order(code, ["const admin = await requireApprovedAdmin", "reservation = await getMaterialAssetUploadReservation", "const object = await getMaterialObjectInfo"]);
  assert.match(code, /reservation\.productId !== productId/);
  assert.match(code, /reservation\.uploadedBy !== admin\.userId/);
});

test("a finalize failure leaves a safe retry path without creating a second version", async () => {
  const [client, finalize, migration, reservationMigration] = await Promise.all([source(clientPath), source(finalizePath), source(migrationPath), source("supabase/migrations/0029_material_storage_integrity_boundary.sql")]);
  assert.match(client, /Vui lòng thử lại/);
  assert.match(finalize, /getMaterialAssetByUploadReservation/);
  assert.match(migration, /CREATE UNIQUE INDEX material_assets_upload_reservation_id_unique/);
  assert.match(reservationMigration, /UNIQUE \(product_id, version\)/i);
});

test("migration 0033 is additive and prior migrations are untouched", async () => {
  const [migration, old] = await Promise.all([source(migrationPath), source("supabase/migrations/0029_material_storage_integrity_boundary.sql")]);
  assert.match(migration, /ALTER TABLE public\.material_asset_upload_reservations/);
  assert.match(migration, /ALTER TABLE public\.material_assets/);
  assert.doesNotMatch(migration, /DO\s*\$\$|SET ROLE|BYPASSRLS|dynamic SQL/i);
  assert.match(old, /CREATE TABLE public\.material_asset_upload_reservations/);
});
